# Generated by Django 4.0.6 on 2022-08-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'PostModel', 'verbose_name_plural': 'PostModels'},
        ),
    ]
